### PR TITLE
Autofocus right OS with JavaScript

### PR DESCRIPTION
**Pull request by txdv**
It automatically focuses the right tab according to the windows.navigator variable!

### CODE REVIEW

**Comment by txdv** [comment]
http://stackoverflow.com/questions/7044944/jquery-javascript-to-detect-os-without-a-plugin

**Comment by akoeplinger** [comment]
Looks nice, thank you!

One question: can we make it so that it doesn't switch if I'm linking to the tab directly like http://www.mono-project.com/download/#download-win even if I'm on another OS?

**Comment by txdv** [comment]
Yeah sure, obvious mistake, was sleepy yesterday so I just pushed what I had and went to sleep.

**Comment by akoeplinger** [comment]
Merged, thank you! I made one small correction which I pushed in https://github.com/mono/website/commit/c35a7c5b54a33f78096589f1f4315fa939adf62c :)

**Pull request merged**
