### PR TITLE
Include C# 4.5 as feature complete.

### PR DESCRIPTION
**Pull request by misaelnieto**
reference: http://www.mono-project.com/docs/about-mono/languages/csharp/

### CODE REVIEW

**Comment by akoeplinger** [comment]
I think you're confusing the language C# with the .NET Framework. There is no C# language specification v4.5, only 1.0 - 5.0.

**Comment by txdv** [comment]
http://en.wikipedia.org/wiki/C_Sharp_(programming_language)#Versions

close it

**Comment by txdv** [comment]
wow, that table just made me realize that 3.0 4.0 and 5.0 have no official ECMA specifications.

that is exactly what all the mono haters said is going to happen

**Comment by akoeplinger** [comment]
@txdv http://tirania.org/blog/archive/2014/Apr-09.html:

> For the last couple of months, the ECMA C# committee has been working on updating the spec to reflect C# 5.

**Pull request closed without merging**
