### PR TITLE
updations to /Install/mac page

### PR DESCRIPTION
**Pull request by aman-saggu-git**
Made changes to documentation of Mono Installation on Mac

### CODE REVIEW

**Comment by akoeplinger** [comment]
- I don't think we need to have a screenshot+explanation for every step of the installer (see the [Windows page](https://github.com/bhallaheemanshu/website/blob/install-mac/docs/getting-started/install/windows/index.md), I think one screenshot is sufficient). The step1 image should be enough.
- Remove the Thumbs.db from the commit
- "on Mac Operating System" -> "on Mac OSX"

**Comment by akoeplinger** [comment]
@bhallaheemanshu Looks like the mono-mac-install.png is missing.

**Comment by akoeplinger** [comment]
Is this ready to go?

If yes, can you please squash the multiple commits into one? Here's how that is done:
1. `git rebase -i HEAD~5`, this starts interactive rebase for the last 5 commits
2. In the editor that pops up, set the action for every commit except the first one to "squash", then save
3. You now have the chance to edit the commit message as well, make sure it's descriptive
4. If everything looks good, do `git push -f origin install-mac` to force-push your local branch to GitHub, overwrites the existing commits in this branch/pull request.

**Comment by Therzok** [comment]
Correction to above.

> In the editor that pops up, set the action for every commit except the first one to "squash", then save

and the first one to "edit"

**Comment by akoeplinger** [comment]
@Therzok if you set the commits to "squash" they'll get meld into the previous commit automatically, not sure why you'd need to set the first one to "edit"?

**Comment by Therzok** [comment]
@akoeplinger Well, edit is too big, probably 'reword' would've worked. I did that so you didn't have to do an extra `git commit --amend` to change the message.

My comment was in regards to:

> You now have the chance to edit the commit message as well, make sure it's descriptive

**Comment by akoeplinger** [comment]
I squashed and merged this in with https://github.com/mono/website/commit/644b13854109c0ddc08a7e2161b01db3b1dccee3. Thanks for your contribution!

**Pull request closed without merging**
