### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by ClemensFMN**
As reported in https://github.com/mono/website/issues/261

If this format is ok for you, I can add the other links and submit as PR...

### CODE REVIEW

**Comment by Therzok** [comment]
This LGTM.

**Comment by akoeplinger** [comment]
Thanks. Please feel free to add the other links!

**Comment by ClemensFMN** [comment]
I took a closer look and have a slightly different proposal than updating index.md:

- There already is a widget overview in the lower part of http://www.mono-project.com/docs/gui/gtksharp/widgets/widget-overview/
- Rename this to index.md, move the widget overview to the top of the page, and complete the overview
- Link to this page on the GTK# landing page http://www.mono-project.com/docs/gui/gtksharp/ , maybe under "References"

What do you tihnk of this?

**Comment by akoeplinger** [comment]
Sounds good too!

**Pull request merged**
