### PR TITLE
Plastic SCM Mono success story for Mono blog

### PR DESCRIPTION
**Pull request by MordodeMaru**
This is the success story of Mono in Plastic SCM's 13 year cross-platform development. It is designed in the form of a blog post for Mono's blog.

### CODE REVIEW

**Review by akoeplinger — APPROVED** [review]
Looks great! I made some small editing changes and moved the blog post date to today.

**Comment by akoeplinger** [comment]
CLA is not required for the website repo, merging.

**Comment by MordodeMaru** [comment]
@akoeplinger Thanks for the ALT titles and the edits, I'm not an expert in markdown. So nothing else required from my side, right? Not event signing the license CLA?

**Comment by lewurm** [comment]
@MordodeMaru it's published here now: https://www.mono-project.com/news/2019/02/13/plastic-scm-a-full-version-control-stack-built-with-mono/

thanks for your contribution 👍

**Comment by MordodeMaru** [comment]
Thanks y'all! There is more OSS dotNET goodies coming this way with the release of FUSESharp which we will release soon. We also released GUITestSharp not long ago:

http://blog.plasticscm.com/2019/01/guitestsharp-multiplatform-gui-testing-dotnet.html

**Pull request merged**
