### PR TITLE
Add fix for "No Application Found Unable to find a matching application ...

### PR DESCRIPTION
**Pull request by texuf**
...for request"

Add fix for "No Application Found Unable to find a matching application for request"

### CODE REVIEW

**Comment by akoeplinger** [comment]
Hmm, I'm curious why this happens on "some systems", maybe a bug?

**Comment by texuf** [comment]
I stumbled on the answer today - that param should be the name specified in the "location" field in the server config. In the example, the location is "/". If that location was changed to "/subdomain" then the resulting command would be .../applications=/subdomain:/var/www/www.domain1.xyz/... 

I think the documentation is just wrong.

**Comment by akoeplinger** [comment]
Hmm, judging from the [FastCGI page](http://www.mono-project.com/docs/web/fastcgi/#how-applications-are-handled-and-how-to-configure-them) the existing line should actually work. `www.domain1.xyz:/:/var/www/www.domain1.xyz/` specifies `www.domain1.xyz` as the hostname, `/` as the virtual root/location and `/var/www/www.domain1.xyz` as the physical path.

The example you added should actually be equivalent to that, except that it listens on all hostnames (note there are only two colon-separated values, instead of three). So it might have something to do with how you access the resource, or rather what the `Host` HTTP-Header specifies. So if you just request http://localhost it won't work, as the fastcgi server only listens for www.domain.xyz.

Can you test whether this is true? If yes, we should probably just add your example as another way to listen on all hostnames.

**Comment by akoeplinger** [comment]
I added some clarification and your example in  https://github.com/mono/website/commit/cb134c656279eef4f72893eeab5d44e99983b940.

**Pull request closed without merging**
