### PR TITLE
Bug Fix in RouteCollection

### PR DESCRIPTION
**Pull request by croconoster**
Improved  ASP.NET MVC 5 Support

### CODE REVIEW

**Comment by akoeplinger** [comment]
I checked that the [PR](https://github.com/mono/mono/pull/1812) mentioned in the [bugzilla issue](https://bugzilla.xamarin.com/show_bug.cgi?id=16475) was merged and is available in the 4.2 branch, so it would be good if someone with permissions on bugzilla could close the issue as fixed (I guess this is also why it wasn't included in the release notes).

Can someone from Xamarin please do this, so I can merge?

**Comment by Therzok** [comment]
Done.

**Comment by akoeplinger** [comment]
Thanks Marius!

**Comment by aammir123** [comment]
I need help as i am getting the same error.

**Pull request merged**
