### PR TITLE
Add Fedora download instructions

### PR DESCRIPTION
**Pull request by harry-cpp**
cc. @directhex 

Notes:
- Should I add a note somewhere stating that it is using CentOS repo?
- ~~I snuck in a `mono-` prefix to the CentOS repo output~~

### CODE REVIEW

**Comment by akoeplinger** [comment]
What if we combine them, i.e. call the tab `CentOS + Fedora` since they're using the same repo?

**Comment by harry-cpp** [comment]
> What if we combine them, i.e. call the tab CentOS + Fedora since they're using the same repo?

CentOS uses yum, Fedora uses dnf, they are a bit different.

**Comment by akoeplinger** [comment]
Thank you!

**Comment by harry-cpp** [comment]
Thank you for merging as well.

PS. Fedora has `sudo` installed by default so you could have kept the command, tho the changed command is fine as well.

**Comment by akoeplinger** [comment]
It doesn't have sudo in the Docker container so I figured I'd make it consistent with the CentOS instructions :)

**Pull request merged**
