### PR TITLE
Wget needed for compilation too.

### PR DESCRIPTION
**Pull request by KhArtNJava**
Mono can't be compiled without wget.

### CODE REVIEW

**Comment by akoeplinger** [comment]
Hmm, wget shouldn't be needed since we already install curl (the build uses either curl or wget, whichever is available).

Could you please show me a log of the failure where you need wget?

I've merged the package name fixes in https://github.com/mono/website/commit/7398976d1d264b7f8bcdfd1b89097fbc8542dc6d, thanks!

**Comment by KhArtNJava** [comment]
OK, I'll try to reproduce that, but it will take some time - my PC is slow.

**Comment by KhArtNJava** [comment]
Really, wget is not needed for compilation Mono from trunk branch.
I think, wget was needed, when I tried to compile Mono 5.2 release... 
Strange, but I 100% remember, that Mono failed to compile, when wget was not installed...

**Comment by KhArtNJava** [comment]
Thank you! )))

**Comment by KhArtNJava** [comment]
I found that!
Will provide full info in 1 hour

**Comment by KhArtNJava** [comment]
First - compilation logs:
[1.zip](https://github.com/mono/website/files/1258581/1.zip)
Try to search in it by string 
wget

It looks like the same code failed in 5.2 Mono, but fixed in trunk with construction like 
```
get-monolite-latest:
	-rm -fr lib/monolite-$(BUILD_PLATFORM)/$(MONO_CORLIB_VERSION)
	-mkdir -p lib/monolite-$(BUILD_PLATFORM)
	cd lib && { (wget -O- $(monolite_url) || curl -L $(monolite_url)) | gzip -d | tar xf - ; }
```
It was root of the issue, why I didn't find it right away - now it shows error, but doesn't fail in trunk.
In any case, I think, that addition of the wget to the cygwin installer command nothing will break. It also will avoid such console message, like 

```
*** Downloading bootstrap required 'monolite-win32/1050700000'
Creating .dep_dirs-basic...
Creating .dep_dirs-basic...
/bin/sh: wget: команда не найдена 
(command not found)
```

Second - I found wget in the makefile of Mono: 
https://github.com/mono/mono/blob/master/Makefile.am

```
win32getdeps:
	wget http://www.go-mono.com/archive/pkgconfig-0.11-20020310.zip
	wget http://www.go-mono.com/archive/glib-2.0.4-20020703.zip 
	wget http://www.go-mono.com/archive/glib-dev-2.0.4-20020703.zip 
	wget http://www.go-mono.com/archive/libiconv-1.7.zip 
	wget http://www.go-mono.com/archive/libiconv-dev-1.7.zip 
	wget http://www.go-mono.com/archive/libintl-0.10.40-20020101.zip
	unzip -n -d / pkgconfig-0.11-20020310.zip
	unzip -n -d / glib-2.0.4-20020703.zip
	unzip -n -d / glib-dev-2.0.4-20020703.zip
	unzip -n -d / libiconv-1.7.zip
	unzip -n -d / libiconv-dev-1.7.zip
	unzip -n -d / libintl-0.10.40-20020101.zip

```

**Comment by akoeplinger** [comment]
Thanks, I've merged the wget addition manually: 5aa43e971c948d0d71fc5395e3ab523754af0ba7

The win32getdeps is leftover and outdated from long ago, I'll remove it (https://github.com/mono/mono/pull/5466).

**Pull request closed without merging**
