### PR TITLE
Changes to docs/index.md and news/index.html

### PR DESCRIPTION
**Pull request by aman-saggu-git**
In news/index.html there was need of line break before first news and I put a horizontal line at end of each News

In docs/index.md I have  placed the contents inside accordion in table

### CODE REVIEW

**Comment by akoeplinger** [comment]
> In news/index.html there was need of line break before first news and I put a horizontal line at end of each News

The line break you put in would be repeated for every item, not just the first, you need to move it outside the foreach. Also, the `<hr/>` should be after the closing `</article>` tag.

> In docs/index.md I have placed the contents inside accordion in table 

I really dislike tables. Can you explain why this is necessary?

**Comment by aman-saggu-git** [comment]
that was just for adding some simple and nice look to contents inside Accordion.

**Comment by aman-saggu-git** [comment]
It looks like this
screenshot

**Comment by aman-saggu-git** [comment]
if you don't like tables i can put panel class there what you suggest

**Comment by aman-saggu-git** [comment]
After Panel it will look like this -

screenshot_panel

**Comment by akoeplinger** [comment]
Yeah, the one with panel looks much better.

Can you separate the changes to news and docs? The two aren't related and should be in their own pull requests.

**Comment by aman-saggu-git** [comment]
ok sure , i will do that with panels.
can you suggest me how can i put them in different pull request . not used git so much

**Comment by akoeplinger** [comment]
It's a bit difficult now because you didn't use a separate branch and did everything in gh-pages.
You'd need to reset your gh-pages branch to the original state (so it doesn't contain any of your commits), then create a new branch for the news changes, apply the changes, push the branch to GitHub and open a PR. Then do the same for the docs changes.

You may want to take a look into using a GUI like [SmartGit](http://www.syntevo.com/smartgit/) or [SourceTree](http://www.sourcetreeapp.com/) if you're having trouble understanding the git command line and reading up some tutorials about branching in git.

**Comment by aman-saggu-git** [comment]
ok, thanks I am looking at these things

**Pull request closed without merging**
