### PR TITLE
Add first post in the profiler stability series.

### PR DESCRIPTION
**Pull request by alexrp**

### CODE REVIEW

**Comment by alexrp** [comment]
cc @kumpera

**Comment by akoeplinger** [comment]
Great post 😄 

Curious: did you run the change/PR through the benchmarking infrastructure as well? If yes, you could link to those results.

**Comment by alexrp** [comment]
Yes, they are here: https://github.com/mono/mono/pull/2881#issuecomment-223415218

I'm not sure that linking to them in this post is a good idea though. I mean, I don't know for how long these results are kept around.

**Comment by akoeplinger** [comment]
@alexrp links are going stale all the time on the Internet, it's not a unique problem to us and if they stay up for a reasonable time that's fine imho 😄

**Comment by migueldeicaza** [comment]
Love it, can we commit, can we change the date to TOday, and commit?

**Comment by lewurm** [comment]
@alexrp we do our best that those links work as long as possible :)

**Pull request merged**
