### PR TITLE
Fix some links

### PR DESCRIPTION
**Pull request by tezaurismosis**
Fix link to PPC topic from IBM
Fix link to elfspec_ppc.pdf

### CODE REVIEW

**Comment by akoeplinger** [comment]
Hmm, not sure linking to some random sourceforge repo is better in this case. Maybe https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/MachORuntime/ ?

Thanks for the corrections!

**Comment by tezaurismosis** [comment]
I can't find pdf-file on official sources, but topic not equal to original specification (92 pages long). So, we can add link to topic at least as a start point to exploration.

**Comment by akoeplinger** [comment]
Sure, feel free to add that in another PR :)

**Comment by tezaurismosis** [comment]
Ok :)

**Pull request merged**
